"""ironbench journal viewer (IH-8): a self-contained HTML timeline of a JSONL
operation journal - the "thin viewer over artifacts" allowed by the 2026-09-07
product decision. No server, no external assets: one HTML file opens offline.

Trust boundary: journal payloads carry firmware/agent-controlled text (serial
data, file names, LLM error strings). Mechanisms that keep it inert: the events
travel to the page as JSON inside a <script type="application/json"> block
where neither "</" (an end tag could terminate the block early) nor "<!--"
(script-data double-escape could make the real closer fail) survives - both
are rewritten in a JSON-compatible, round-tripping way; the table renders
client-side through textContent only; template tokens are substituted
section-by-section so a value containing a token string can never be expanded
by a later pass. The client JS is dependency-free and is not executed by
pytest - its correctness is pinned by structure tests plus manual browser
review rounds.

Unparseable lines are counted and stated in the header, never silently dropped
("no log = didn't happen"). Past MAX_EVENTS the middle of the journal is
omitted from the view (the file itself is untouched) and the omission is
stated in the header.
"""

from __future__ import annotations

import html
import json
import math
import re
import time
from datetime import datetime
from pathlib import Path

# A local artifact, not a big-data tool: the cap bounds the generated file.
MAX_EVENTS = 100_000

# Row shape consumed by the page: {"time", "actor", "kind", "conn", "p"} where
# p is the payload with the service keys stripped (they became the columns).
Row = dict

VIEW_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>ironbench - journal __SOURCE__</title>
<style>
  body { font-family: -apple-system, "Segoe UI", sans-serif; margin: 1.5rem; color: #222; }
  h1 { font-size: 1.2rem; }
  #summary { color: #555; font-size: 0.9rem; margin: 0.4rem 0 0.8rem; }
  #bar { margin-bottom: 0.6rem; display: flex; gap: 0.6rem; flex-wrap: wrap; }
  #bar select, #bar input { padding: 3px 6px; }
  #bar input { flex: 1; min-width: 12rem; }
  #count { color: #777; font-size: 0.85rem; margin: 0.4rem 0; }
  table { border-collapse: collapse; width: 100%; table-layout: fixed; }
  th, td { border: 1px solid #ddd; padding: 4px 8px; text-align: left;
            vertical-align: top; overflow-wrap: anywhere; }
  th { background: #f4f4f4; position: sticky; top: 0; }
  td.t { white-space: nowrap; font-size: 0.85rem; }
  td.k { font-weight: 600; }
  td.p { font-family: Consolas, monospace; font-size: 0.82rem; white-space: pre-wrap; }
  tr.bad td.k { color: #b3261e; }
  tr.ok td.k { color: #0a7d24; }
  #more { margin: 0.6rem 0; }
  footer { margin-top: 1.2rem; color: #777; font-size: 0.85rem; }
</style>
</head>
<body>
<h1>ironbench journal timeline - __SOURCE__</h1>
<div id="summary">__SUMMARY__</div>
<div id="bar">
  <select id="f-kind"><option value="">kind: all</option></select>
  <select id="f-actor"><option value="">actor: all</option></select>
  <select id="f-conn"><option value="">conn: all</option></select>
  <input id="f-text" type="search" placeholder="search in events...">
</div>
<div id="count"></div>
<table>
<thead><tr><th style="width:11ch">time</th><th style="width:9ch">actor</th>
<th style="width:16ch">kind</th><th style="width:12ch">conn</th><th>payload</th></tr></thead>
<tbody id="rows"></tbody>
</table>
<div id="more"><button id="more-btn" hidden>show more</button></div>
<footer>Generated by ironbench · events are the JSONL operation journal of io-core
(who/when/what/response) · all values are rendered as text, never as HTML</footer>
<script id="ih-data" type="application/json">__DATA_JSON__</script>
<script>
"use strict";
var DATA = JSON.parse(document.getElementById("ih-data").textContent);
var ROWS = DATA.rows, SHOWN = 0, CHUNK = 500;

function el(tag, cls, text) {
  var node = document.createElement(tag);
  if (cls) node.className = cls;
  if (text !== undefined) node.textContent = text;  // the only sink: plain text
  return node;
}

function payloadText(row) {
  var keys = Object.keys(row.p).sort();
  if (!keys.length) return "";
  return keys.map(function (k) { return k + ": " + JSON.stringify(row.p[k]); }).join("\\n");
}

function rowClass(row) {
  var k = row.kind || "";
  if (/(^|_)(fail|failed|violation|error|timeout)($|_)/.test(k)) return "bad";
  if (k === "task_result" || k === "attempt_result") return row.p && row.p.passed ? "ok" : "bad";
  return "";
}

function renderChunk() {
  var tbody = document.getElementById("rows");
  var end = Math.min(SHOWN + CHUNK, ROWS.length);
  for (var i = SHOWN; i < end; i++) {
    var row = ROWS[i], tr = el("tr", rowClass(row));
    tr.appendChild(el("td", "t", row.time));
    tr.appendChild(el("td", "", row.actor));
    tr.appendChild(el("td", "k", row.kind));
    tr.appendChild(el("td", "", row.conn));
    tr.appendChild(el("td", "p", payloadText(row)));
    tbody.appendChild(tr);
  }
  SHOWN = end;
  document.getElementById("count").textContent =
    "showing " + SHOWN + " of " + ROWS.length + " event(s)";
  document.getElementById("more-btn").hidden = SHOWN >= ROWS.length;
}

function fill(select, values, label) {
  values.forEach(function (v) {
    var opt = el("option", "", label + v);
    opt.value = v;
    select.appendChild(opt);
  });
}

function applyFilters() {
  var kind = document.getElementById("f-kind").value;
  var actor = document.getElementById("f-actor").value;
  var conn = document.getElementById("f-conn").value;
  var text = document.getElementById("f-text").value.toLowerCase();
  ROWS = DATA.rows.filter(function (row) {
    if (kind && row.kind !== kind) return false;
    if (actor && row.actor !== actor) return false;
    if (conn && row.conn !== conn) return false;
    if (text && JSON.stringify(row).toLowerCase().indexOf(text) < 0) return false;
    return true;
  });
  SHOWN = 0;
  document.getElementById("rows").textContent = "";
  renderChunk();
}

fill(document.getElementById("f-kind"), DATA.kinds, "kind: ");
fill(document.getElementById("f-actor"), DATA.actors, "actor: ");
fill(document.getElementById("f-conn"), DATA.conns, "conn: ");
document.getElementById("more-btn").addEventListener("click", renderChunk);
["f-kind", "f-actor", "f-conn"].forEach(function (id) {
  document.getElementById(id).addEventListener("change", applyFilters);
});
var debounce;
document.getElementById("f-text").addEventListener("input", function () {
  clearTimeout(debounce);
  debounce = setTimeout(applyFilters, 200);
});
renderChunk();
</script>
</body>
</html>
"""

SERVICE_KEYS = frozenset({"ts", "seq", "actor", "kind"})


def load_events_lenient(path: Path) -> tuple[list[dict], int]:
    """All event dicts of the JSONL journal; unparseable lines are counted,
    not dropped silently. Returns (events, skipped)."""
    events: list[dict] = []
    skipped = 0
    text = path.read_text(encoding="utf-8", errors="replace")
    for line in text.splitlines():
        if not line.strip():
            continue
        try:
            rec = json.loads(line)
        except json.JSONDecodeError:
            skipped += 1
            continue
        if not isinstance(rec, dict):
            skipped += 1
            continue
        events.append(rec)
    return events, skipped


def _row_time(ts: float) -> str:
    try:
        return datetime.fromtimestamp(ts).astimezone().isoformat(timespec="milliseconds")
    except (OSError, OverflowError, ValueError):
        # pre-epoch timestamps are not representable in the local timezone on
        # Windows; the raw value keeps the view alive on junk ts fields
        return str(ts)


def _as_str(value) -> str:
    return value if isinstance(value, str) else json.dumps(value, ensure_ascii=False, default=str)


def _sanitize(value):
    """Non-finite floats become strings: json.dumps would emit bare NaN/
    Infinity, which Python accepts but a browser's JSON.parse rejects - the
    whole dynamic view would silently die client-side. Iterative on purpose:
    hostile payloads can be nested deeper than the interpreter stack (json's
    C scanner handles them fine, plain recursion would not)."""
    stack = [value]
    while stack:
        node = stack.pop()
        if isinstance(node, dict):
            items = node.items()
        elif isinstance(node, list):
            items = enumerate(node)
        else:
            continue
        for key, val in items:
            if isinstance(val, float) and not math.isfinite(val):
                node[key] = str(val)
            elif isinstance(val, (dict, list)):
                stack.append(val)
    return value


def build_view(journal: Path, *, max_events: int = MAX_EVENTS, now: float | None = None) -> dict:
    """The view model: normalized rows (file order, stable-sorted by ts),
    facets for the filters, and honest counters for skipped/omitted lines."""
    events, skipped = load_events_lenient(journal)
    events.sort(key=lambda e: e.get("ts", 0.0) if isinstance(e.get("ts"), (int, float)) else 0.0)
    total = len(events)
    omitted = 0
    if total > max_events:
        half = max_events // 2
        omitted = total - max_events
        events = events[:half] + events[-half:]
    rows: list[Row] = []
    for e in events:
        ts = e.get("ts")
        rows.append(
            {
                "time": _row_time(ts) if isinstance(ts, (int, float)) else "",
                "actor": _as_str(e.get("actor", "?")),
                "kind": _as_str(e.get("kind", "?")),
                "conn": _as_str(e["conn"]) if "conn" in e else "",
                "p": _sanitize(
                    {k: v for k, v in e.items() if k not in SERVICE_KEYS and k != "conn"}
                ),
            }
        )
    stamps = [e["ts"] for e in events if isinstance(e.get("ts"), (int, float))]

    def facet(key: str) -> list[str]:
        return sorted({_as_str(e[key]) for e in events if key in e})

    return {
        "source": journal.name,
        "generated": datetime.fromtimestamp(now if now is not None else time.time())
        .astimezone()
        .strftime("%Y-%m-%d %H:%M:%S %z"),
        "rows": rows,
        "file_events": total,
        "shown_events": len(rows),
        "skipped_lines": skipped,
        "omitted_events": omitted,
        "span": [_row_time(stamps[0]), _row_time(stamps[-1])] if stamps else [],
        "kinds": facet("kind"),
        "actors": facet("actor"),
        "conns": facet("conn"),
    }


def _summary_html(view: dict) -> str:
    parts = [
        f"{view['file_events']} event(s)",
        f"{view['shown_events']} shown",
    ]
    if view["skipped_lines"]:
        parts.append(f"<b>{view['skipped_lines']} unparseable line(s) skipped</b>")
    if view["omitted_events"]:
        parts.append(f"<b>{view['omitted_events']} middle event(s) omitted</b>")
    if view["span"]:
        parts.append(f"span {html.escape(view['span'][0])} .. {html.escape(view['span'][1])}")
    parts.append(f"generated {html.escape(view['generated'])}")
    return " · ".join(parts)


def render_html(view: dict) -> str:
    """The self-contained page. Token substitution is single-pass over the
    template: substituted values are never rescanned, so a source/payload
    value that happens to contain a token string cannot be expanded later
    (token expansion = HTML injection). Data embedding invariant: the JSON
    blob may contain neither "</" (an end tag could terminate the block
    early) nor "<!--" (script-data double-escape could make the real closer
    fail) - both are rewritten in a JSON-compatible, round-tripping way."""
    values = {
        "SOURCE": html.escape(view["source"]),
        "SUMMARY": _summary_html(view),
    }
    blob = json.dumps(view, ensure_ascii=False, default=str)
    blob = blob.replace("</", "<\\/").replace("<!--", "<\\u0021--")
    parts: list[str] = []
    pos = 0
    for m in re.finditer(r"__(SOURCE|SUMMARY|DATA_JSON)__", VIEW_TEMPLATE):
        parts.append(VIEW_TEMPLATE[pos : m.start()])
        parts.append(blob if m.group(1) == "DATA_JSON" else values[m.group(1)])
        pos = m.end()
    parts.append(VIEW_TEMPLATE[pos:])
    return "".join(parts)


def write_view(journal: Path, out_file: Path, *, max_events: int = MAX_EVENTS) -> tuple[Path, dict]:
    """The view HTML next to the journal; returns (out_file, view). Refuses to
    overwrite the journal itself: the view must never destroy the artifact it
    renders ("no log = didn't happen")."""
    if out_file.exists() and out_file.resolve() == journal.resolve():
        raise ValueError(f"refusing to overwrite the journal with its view: {out_file}")
    view = build_view(journal, max_events=max_events)
    out_file.parent.mkdir(parents=True, exist_ok=True)
    out_file.write_text(render_html(view), encoding="utf-8")
    return out_file, view
