"""ironbench report (2.5): aggregates solve-campaign results into JSON + HTML.

Input - a campaigns directory (default .ironbench/solve); results.jsonl files
written by the solve CLI are searched recursively. Metrics per (model, task)
pair: attempts, solved, success rate (solved/attempts) and pass@k - "solved by
at least one of k attempts", k = the number of attempts for that pair.

Honesty policy (IH-31): an attempt that failed at the environment level
(error_kind == "infra") is NOT a failure of the model - it never got a
working run. Infra attempts are excluded from success rates and from the
pass@k denominator; a pair whose attempts are ALL infra is marked
"incomplete" and shown as n/a. Unparseable results.jsonl lines are skipped
and reported ("N unparseable in <path>") instead of killing every campaign.

Taxonomy: when a map of task metadata (class tags + level from task.yaml) is
given, the report gains a per-class profile - the model's success rate on each
class (io/data/protocol/fsm/control/resilience/debug) instead of a single pass@k
number. A task with several tags lands in each of them; tasks without metadata
(deleted, or the map was not passed) are not part of the profile.
"""

from __future__ import annotations

import dataclasses
import json
from collections import defaultdict
from datetime import UTC, datetime
from html import escape as html_escape
from pathlib import Path

HTML_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>ironbench - report</title>
<style>
  body {{ font-family: -apple-system, "Segoe UI", sans-serif; margin: 2rem; color: #222; }}
  h1 {{ font-size: 1.3rem; }}
  table {{ border-collapse: collapse; margin-top: 1rem; }}
  th, td {{ border: 1px solid #ccc; padding: 6px 14px; text-align: left; }}
  th {{ background: #f4f4f4; }}
  .pass {{ color: #0a7d24; font-weight: 600; }}
  .fail {{ color: #b3261e; font-weight: 600; }}
  footer {{ margin-top: 1.5rem; color: #777; font-size: 0.85rem; }}
</style>
</head>
<body>
<h1>ironbench report {campaign}</h1>
<table>
<tr><th>Model</th><th>Task</th><th>Attempts</th><th>Solved</th><th>Success rate</th><th>Avg iterations</th><th>Avg time, s</th></tr>
{rows}
</table>
<footer>Generated by ironbench · pass@k = fraction of pairs solved by at least one of k attempts: {pass_at_k}<br>
{honesty_note}</footer>
{profile_table}
</body>
</html>
"""


@dataclasses.dataclass(frozen=True)
class GroupStats:
    model: str
    task: str
    attempts: int
    solved: int
    total_iterations: int
    total_duration: float = 0.0
    # IH-31 honesty: infra attempts (environment failures the model cannot
    # fix) are excluded from success_rate and pass@k
    infra_failures: int = 0

    @property
    def effective_attempts(self) -> int:
        return self.attempts - self.infra_failures

    @property
    def incomplete(self) -> bool:
        """True when every attempt died at the environment level - the pair
        says nothing about the model and is excluded from pass@k."""
        return self.attempts > 0 and self.effective_attempts == 0

    @property
    def success_rate(self) -> float | None:
        """solved / live attempts; None for an incomplete pair (all infra)."""
        if self.effective_attempts <= 0:
            return None
        return round(self.solved / self.effective_attempts, 2)

    @property
    def avg_iterations(self) -> float:
        return round(self.total_iterations / self.attempts, 1) if self.attempts else 0.0

    @property
    def avg_duration(self) -> float:
        """Average attempt time, seconds - the latency axis next to pass/fail."""
        return round(self.total_duration / self.attempts, 1) if self.attempts else 0.0

    @property
    def passed(self) -> bool:
        return self.solved > 0


def load_results(solve_dir: Path) -> tuple[list[dict], list[dict]]:
    """All attempt_result records from results.jsonl in the campaigns
    directory (recursive).

    Returns (records, unparseable): unparseable lines are SKIPPED, not a
    crash - one truncated line from a killed process must not destroy every
    campaign's report. Each entry is {"file": <path>, "lines": <count>} so
    the report can say honestly what was dropped and where.
    """
    records: list[dict] = []
    unparseable: dict[str, int] = {}
    for path in sorted(solve_dir.rglob("results.jsonl")):
        bad = 0
        for line in path.read_text(encoding="utf-8").splitlines():
            if not line.strip():
                continue
            try:
                rec = json.loads(line)
            except ValueError:
                bad += 1
                continue
            if not isinstance(rec, dict):
                bad += 1
                continue
            records.append(rec)
        if bad:
            unparseable[str(path)] = bad
    return records, [{"file": f, "lines": n} for f, n in sorted(unparseable.items())]


def aggregate(records: list[dict]) -> list[GroupStats]:
    """Grouping (model, task) -> stats; sorted by model, then task. Records
    without error_kind (old campaigns) count as live attempts."""
    groups: dict[tuple[str, str], list[float]] = defaultdict(lambda: [0, 0, 0, 0.0, 0])
    for rec in records:
        stats = groups[(rec.get("model", "?"), rec.get("task", "?"))]
        stats[0] += 1
        stats[1] += 1 if rec.get("solved") else 0
        stats[2] += int(rec.get("iterations", 0))
        stats[3] += float(rec.get("duration_sec", 0))
        if rec.get("error_kind") == "infra" and not rec.get("solved"):
            stats[4] += 1
    return [
        GroupStats(
            model=model,
            task=task,
            attempts=a,
            solved=s,
            total_iterations=i,
            total_duration=d,
            infra_failures=infra,
        )
        for (model, task), (a, s, i, d, infra) in sorted(groups.items())
    ]


def build_report(solve_dir: Path, task_meta: dict | None = None) -> dict:
    """Campaign aggregate: JSON structure + pass@k (fraction of pairs with at least
    one solution). task_meta: task name -> {"tags": [...], "level": int|None} - for
    the per-class profile.

    pass@k's denominator counts only pairs with at least one live attempt
    (IH-31): an all-infra pair is a broken environment, not a model failure.
    """
    records, unparseable = load_results(solve_dir)
    stats = aggregate(records)
    complete = [s for s in stats if not s.incomplete]
    pass_at_k = (
        round(sum(1 for s in complete if s.passed) / len(complete), 2) if complete else 0.0
    )
    meta = task_meta or {}

    def meta_of(name: str) -> dict:
        return meta.get(name, {"tags": [], "level": None})

    return {
        "campaign": solve_dir.name,
        "models": sorted({s.model for s in stats}),
        "tasks": sorted({s.task for s in stats}),
        "pass_at_k": pass_at_k,
        "groups": [dataclasses.asdict(s) | {
            "success_rate": s.success_rate,
            "avg_iterations": s.avg_iterations,
            "avg_duration": s.avg_duration,
            "passed": s.passed,
            "incomplete": s.incomplete,
            "tags": meta_of(s.task)["tags"],
            "level": meta_of(s.task)["level"],
        } for s in stats],
        "class_profile": class_profile(records, meta),
        # honesty notes: what the report could not read (IH-31)
        "unparseable": unparseable,
    }


def class_profile(records: list[dict], task_meta: dict) -> dict:
    """Per-class profile: (model, tag) -> attempts/solved/success rate.
    Infra attempts (error_kind=infra, unsolved) are excluded - they never
    exercised the class."""
    raw: dict[str, dict[str, list[int]]] = {}
    for rec in records:
        meta = task_meta.get(rec.get("task", "?"))
        if not meta:
            continue
        if rec.get("error_kind") == "infra" and not rec.get("solved"):
            continue
        for tag in meta.get("tags", ()):
            cell = raw.setdefault(rec.get("model", "?"), {}).setdefault(tag, [0, 0])
            cell[0] += 1
            cell[1] += 1 if rec.get("solved") else 0
    return {
        model: {
            tag: {
                "attempts": attempts,
                "solved": solved,
                "success_rate": round(solved / attempts, 2) if attempts else 0.0,
            }
            for tag, (attempts, solved) in sorted(cells.items())
        }
        for model, cells in sorted(raw.items())
    }


def render_html(report: dict) -> str:
    rows = []
    for g in report["groups"]:
        cls = "pass" if g["passed"] else "fail"
        meta = " · ".join(
            filter(None, (", ".join(g.get("tags", ())), f"lvl {g['level']}" if g.get("level") else ""))
        )
        # an incomplete pair (all attempts infra) has no honest success rate
        rate = "n/a" if g.get("incomplete") else f'{g["success_rate"]:.0%}'
        rate_cls = f' class="{cls}"' if not g.get("incomplete") else ""
        rows.append(
            f'<tr><td>{html_escape(g["model"])}</td><td>{html_escape(g["task"])}'
            + (f' <small>({html_escape(meta)})</small>' if meta else "")
            + f'</td><td>{g["attempts"]}</td><td>{g["solved"]}</td>'
            + f'<td{rate_cls}>{rate}</td>'
            + f"<td>{g['avg_iterations']}</td><td>{g['avg_duration']}</td></tr>"
        )
    profile_table = _render_profile_table(report.get("class_profile") or {})
    honesty_note = _honesty_note(report)
    return HTML_TEMPLATE.format(
        campaign=html_escape(report["campaign"]),
        rows="\n".join(rows),
        pass_at_k=f"{report['pass_at_k']:.0%}",
        honesty_note=honesty_note,
        profile_table=profile_table,
    )


def _honesty_note(report: dict) -> str:
    """Footer notes for everything the report had to be honest about."""
    notes = []
    if any(g.get("infra_failures") or g.get("incomplete") for g in report["groups"]):
        notes.append(
            "attempts marked infra (environment failures) are excluded from "
            "success rates and pass@k; incomplete pairs are shown as n/a"
        )
    unparseable = report.get("unparseable") or []
    if unparseable:
        dropped = ", ".join(f"{u['lines']} in {u['file']}" for u in unparseable)
        notes.append(f"unparseable results.jsonl lines skipped: {dropped}")
    return "<br>".join(html_escape(n) for n in notes)


def _render_profile_table(profile: dict) -> str:
    """HTML of the "Class profile" table; empty string when there is no profile."""
    if not profile:
        return ""
    tags = sorted({t for cells in profile.values() for t in cells})
    head = "".join(f"<th>{html_escape(t)}</th>" for t in tags)
    rows = []
    for model, cells in profile.items():
        cells_html = "".join(
            f'<td>{cells[t]["solved"]}/{cells[t]["attempts"]} ({cells[t]["success_rate"]:.0%})</td>'
            if t in cells
            else "<td>-</td>"
            for t in tags
        )
        rows.append(f"<tr><td>{html_escape(model)}</td>{cells_html}</tr>")
    return (
        "<h1>Class profile (solved/attempts, attempt success rate)</h1>"
        f'<table><tr><th>Model</th>{head}</tr>{"".join(rows)}</table>'
    )


def write_report(solve_dir: Path, out_dir: Path, task_meta: dict | None = None) -> tuple[Path, Path]:
    """JSON + HTML of the report; returns their paths. task_meta - the tags/levels map."""
    report = build_report(solve_dir, task_meta)
    out_dir.mkdir(parents=True, exist_ok=True)
    json_path = out_dir / "report.json"
    html_path = out_dir / "report.html"
    json_path.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    html_path.write_text(render_html(report), encoding="utf-8")
    return json_path, html_path


LEADERBOARD_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>ironbench leaderboard</title>
<style>
  body {{ font-family: -apple-system, "Segoe UI", sans-serif; margin: 2rem; color: #222; }}
  h1 {{ font-size: 1.3rem; }}
  table {{ border-collapse: collapse; margin-top: 1rem; }}
  th, td {{ border: 1px solid #ccc; padding: 6px 14px; text-align: left; }}
  th {{ background: #f4f4f4; }}
  footer {{ margin-top: 1.5rem; color: #777; font-size: 0.85rem; }}
</style>
</head>
<body>
<h1>ironbench leaderboard - firmware-agent benchmark</h1>
<table>
<tr><th>Model</th><th>pass@k</th><th>Tasks</th>{tag_head}</tr>
{rows}
</table>
<footer>{generated} · pass@k = fraction of the model's (model, task) pairs solved by at
least one attempt · class columns: solved/attempts (attempt success rate) · infra
attempts (environment failures) excluded · Generated by ironbench</footer>
</body>
</html>
"""


def render_leaderboard(report: dict, generated: str | None = None) -> str:
    """Standalone leaderboard page for GitHub Pages: model x class success table.

    Unlike render_html (one campaign view), this one aggregates across all
    campaigns in the solve directory - one row per model. Incomplete pairs
    (every attempt infra) do not count against the model's pass@k (IH-31).
    """
    profile = report.get("class_profile") or {}
    tags = sorted({t for cells in profile.values() for t in cells})
    pairs: dict[str, list[int]] = defaultdict(lambda: [0, 0])
    for g in report["groups"]:
        if g.get("incomplete"):
            continue
        cell = pairs[g["model"]]
        cell[0] += 1
        cell[1] += 1 if g["passed"] else 0
    rows = []
    for model in sorted(pairs):
        attempts, solved = pairs[model]
        pass_at_k = f"{solved / attempts:.0%}" if attempts else "-"
        cells_html = "".join(
            f'<td>{c["solved"]}/{c["attempts"]} ({c["success_rate"]:.0%})</td>'
            if (c := profile.get(model, {}).get(tag))
            else "<td>-</td>"
            for tag in tags
        )
        rows.append(
            f"<tr><td>{html_escape(model)}</td><td>{pass_at_k}</td>"
            f"<td>{attempts}</td>{cells_html}</tr>"
        )
    tag_head = "".join(f"<th>{html_escape(t)}</th>" for t in tags)
    return LEADERBOARD_TEMPLATE.format(
        tag_head=tag_head,
        rows="\n".join(rows),
        generated=generated or datetime.now(UTC).strftime("%Y-%m-%d UTC"),
    )
